add ability to ignore null properties
mrstebo/RestSharp.SnakeCaseSerializer pull request #1
Opened 2017-11-18 18:07 UTC by mgraf1

Added a property `IgnoreNullProperties` that when true prevents null properties from being serialized.

2017-11-21 14:01 UTC, mrstebo requested changes
Nicely implemented 👍 
Just need to change the naming format of that private variable and I'll approve 🎉

2017-11-21 14:01 UTC, mrstebo commented on src/RestSharp.SnakeCaseSerializer.Tests/SnakeCaseSerializationStrategyTests.cs
> +        private SnakeCaseSerializationStrategy strategyUnderTest;
Naming format for private variables should be `_myVariable`. Although for some reason VS for Mac doesn't seem to like that format 😒

2017-11-21 14:01 UTC, mrstebo commented on src/RestSharp.SnakeCaseSerializer.Tests/SnakeCaseSerializationStrategyTests.cs
> +        public void WhenIgnoringNullValues_Should_Not_Serialize_Null_Properties()
Great job! 👍

2017-11-22 01:01 UTC, mgraf1 commented
Thanks for the feedback! Change has been made.

2017-11-22 08:20 UTC, mrstebo commented
Awesome. Just need to wait for AppVeyor to start working again so we know everything still works 😅

2017-11-24 08:29 UTC, mrstebo commented
AppVeyor seems to not want to build this...but looks like it could be something on their end, so I'll just merge this in 👍

2017-11-24 08:30 UTC, merged